/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        'proxima': ['Proxima Nova', 'sans-serif'],
        'sans': ['Proxima Nova', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(-10deg)' },
          '75%': { transform: 'rotate(10deg)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-10%)' },
          '75%': { transform: 'translateX(10%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        'float-delayed': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-15px)' },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        wiggle: 'wiggle 1s ease-in-out infinite',
        shake: 'shake 0.5s ease-in-out infinite',
        float: 'float 6s ease-in-out infinite',
        'float-delayed': 'float-delayed 8s ease-in-out infinite',
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        zerrah: {
          red: '#D94B5A',
          orange: '#F89C4E',
          yellow: '#F9E28C',
          green: '#8FD19E',
          blue: '#4A90C2',
          lightgreen: '#E2F29B',
          deepgreen: '#4B8F6E',
          deepblue: '#22577A',
        },
        // Warm, emotionally resonant colors
        sage: {
          50: '#F7F9F6',
          100: '#E8F0E3',
          200: '#D1E1C7',
          300: '#B3D1A3',
          400: '#8FB87A',
          500: '#6B9F51',
          600: '#5A8A44',
          700: '#4A7537',
          800: '#3A602A',
          900: '#2A4B1D',
        },
        warm: {
          50: '#FEFCF9',
          100: '#FDF7F0',
          200: '#FBEEDD',
          300: '#F8E0C4',
          400: '#F4CCA3',
          500: '#F0B882',
          600: '#E8A061',
          700: '#D88A4A',
          800: '#C67333',
          900: '#B45C1C',
        },
        cream: {
          50: '#FEFEFD',
          100: '#FDFCFA',
          200: '#FBF9F5',
          300: '#F8F4ED',
          400: '#F5EFE4',
          500: '#F2E9DB',
          600: '#E8DCC8',
          700: '#DECFB5',
          800: '#D4C2A2',
          900: '#CAB58F',
        },
        terracotta: {
          50: '#FEF7F5',
          100: '#FDEBE7',
          200: '#FBD8D0',
          300: '#F8BEB1',
          400: '#F49A85',
          500: '#F07659',
          600: '#E85A3A',
          700: '#D44A2B',
          800: '#B03D24',
          900: '#8C301D',
        },
        honey: {
          50: '#FEFCF7',
          100: '#FDF8ED',
          200: '#FBF0D6',
          300: '#F8E4B8',
          400: '#F5D494',
          500: '#F2C470',
          600: '#E8B04C',
          700: '#DE9C28',
          800: '#D48804',
          900: '#CA74E0',
        },
        sky: {
          50: '#F0F9FF',
          100: '#E0F2FE',
          200: '#BAE6FD',
          300: '#7DD3FC',
          400: '#38BDF8',
          500: '#0EA5E9',
          600: '#0284C7',
          700: '#0369A1',
          800: '#075985',
          900: '#0C4A6E',
        },
        brand: {
          teal: '#16626D',
          emerald: '#18A07A',
          amber: '#F59E0B',
          oxblood: '#5E1614',
          sage: '#A7D58E',
        },
      },
      boxShadow: {
        brand: '0 10px 40px rgba(0,0,0,.06)',
      },
      backgroundImage: {
        'brand-radial':
          'radial-gradient(60% 50% at 20% 0%, rgba(22,98,109,.08), transparent), radial-gradient(40% 35% at 80% 100%, rgba(167,213,142,.10), transparent)',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} 